#!/bin/bash


scp -r dist/* cp@xrat.ctsu.ox.ac.uk:/user/cp/public_html/bbquiz/matrix/

exit 0

# 2016-04-14 q108-vlubuntu ssh to xrat no longer works
# 2016-09-28 yes it does, use full name: cp@xrat.ctsu.ox.ac.uk

#if [ -d "dist" ]; then          # we're on a machine where dist has been built, i.e. q108-vlubuntu or yoga3-vlubuntu

APPNAME="hoops"
SERVER="xrat"
USER="webman"

echo "HOSTNAME: $HOSTNAME. APPNAME: $APPNAME"

echo "Make sure you have run gulp to build into ./dist, and the folder $APPNAME must exist and be writable on the server"
read -rsp $'Press any key to continue...\n' -n1 key

if [ "$HOSTNAME" = "Q108" ]; then          # we can ssh to xrat but gulp build doesn't work
    echo "getting dist.tgz from remote..."
    scp drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/$APPNAME/dist.tgz .
    echo "unzipping..."
    tar xzf dist.tgz  # unzip it to a folder named something else
    echo "uploading..."
    scp -r ./dist/* webman@xrat:/user/webman/www/$APPNAME/
else                            # we're on a machine where dist has been built, 
                                # but there is no access to xrat, e.g. q108-vlubuntu or yoga3-vlubuntu
    if [ -d "dist" ]; then
        echo "'dist' exists, creating zip..."
        tar czf dist.tgz dist       # zip it good
        echo "uploading..."
        scp dist.tgz drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/$APPNAME/ # upload
    else
        echo "no 'dist' directory, exiting"
        exit 0
    fi
fi
echo "done"

# add -v for verbose debugging

# can use ssh config file, e.g ~/.ssh/config, to automate somethings, but not the password
# http://serverfault.com/questions/535028/adding-password-to-ssh-config/535031
# $ man ssh_config

# problems with this - doesn't seem to update files
#gulp --gulpfile gulp-ssh.js sftp-push-xrat
