#!/bin/bash

# http://stackoverflow.com/questions/216995/
shopt -s extglob # can then exclude with wildcards, e.g.: !(images)
#scp "./dist/* !(images)" drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/hoops/


echo "Remember to run gulp first to build into ./dist"
read -rsp $'Press any key to continue...\n' -n1 key
exit 0
scp -r ./dist/scripts/* drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/hoops/scripts/ # add -v for verbose debugging
scp -r ./dist/styles/* drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/hoops/styles/
scp ./dist/* drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/hoops/