#!/bin/bash
# add -v for verbose debugging

# http://stackoverflow.com/questions/216995/
#shopt -s extglob # can then exclude with wildcards, e.g.: !(images)
#scp "./dist/* !(images)" $REMOTEUSER@$REMOTEHOST:$REMOTEPATH

REMOTEHOST="oqsweb.ndph.ox.ac.uk"
REMOTEUSER="cp"
REMOTEROOT="/user/cp/cjb/proj/bb-quizzes/"  # http://red.ctsu.ox.ac.uk/~cp/cjb/

# if [ -z "$1" ]
# then
#     DIR="matrix"
#     echo "No argument supplied, defaulting to '$DIR'"
# else
#     DIR=$1
# fi

REMOTEPATH=$REMOTEROOT #$DIR

#echo "Copying entire repo to $REMOTEUSER@$REMOTEHOST:$REMOTEPATH"
echo "rsyncing entire repo to $REMOTEUSER@$REMOTEHOST:$REMOTEPATH"
echo "(dirs must exist on server already? only base target directory)"
read -rsp $'Press any key to continue...\n' -n1 key

rsync -ra ./ $REMOTEUSER@$REMOTEHOST:$REMOTEPATH

exit 0
