#!/bin/bash

# http://stackoverflow.com/questions/216995/
shopt -s extglob # can then exclude with wildcards, e.g.: !(images)
#scp "./dist/* !(images)" drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/matrix/

echo "Remember to run gulp first to build into ./dist"
scp -r ./dist/scripts/* drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/matrix/scripts/ # add -v for verbose debugging
scp -r ./dist/styles/* drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/matrix/styles/
scp ./dist/* drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/matrix/