#!/bin/bash

shopt -s exglob # can then exclude with wildcards, e.g.: !(images)

scp -r ./dist/scripts/* drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/matrix/scripts/ # add -v for verbose debugging
scp -r ./dist/styles/* drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/matrix/styles/
#scp "./dist/* !(images)" drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/matrix/
scp ./dist/* drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/matrix/

#gulp --gulpfile gulp-ssh.js sftp-push-webfaction # problems with this - doesn't seem to update files
