#!/bin/sh
# no tcsh, csh on webman@oqsweb

#end = $argv[1]
end='test'
own='cp_web_'
xdb=$own$end

#echo "xdb: $xdb"
#exit 0

destroydb $xdb
createdb -i $xdb
./create-create.py > ./create.sql
sql $xdb < create.sql

sql iidbdb << GRANTED
grant access on database cp_web_test to apache;
\p\g
\q
GRANTED
