#!/bin/bash
# add -v for verbose debugging

REMOTEHOST="red.ctsu.ox.ac.uk"
REMOTEUSER="cp"
REMOTEROOT="/user/cp/Projects/bb-quizzes/db/sql"  # http://red.ctsu.ox.ac.uk/~cp/cjb/
REMOTEPATH=$REMOTEROOT #$DIR

echo "Copying folder to $REMOTEUSER@$REMOTEHOST:$REMOTEPATH"
echo "(dirs must exist on server already? only base target directory)"
read -rsp $'Press any key to continue...\n' -n1 key
scp -r * $REMOTEUSER@$REMOTEHOST:$REMOTEPATH
exit 0
