#!/bin/bash

# add -v for verbose debugging
scp -r index.html drkvogel@web456.webfaction.com:/home/drkvogel/webapps/main/responsive/tables/

# problems with this - doesn't seem to update files
#gulp --gulpfile gulp-ssh.js sftp-push-webfaction
